[package]
name = "zombie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zombie_core = { path = "../zombie_core" }
zombie_macro = { path = "../zombie_macro" }
